# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-19 00:42
from __future__ import unicode_literals

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [
        ('Adres_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zlecenie',
            name='data_zlozenia',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 19, 0, 42, 3, 471154, tzinfo=utc)),
        ),
    ]
