# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-20 12:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('Adres_app', '0003_auto_20171219_0142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zlecenie',
            name='adres_dostawy',
        ),
        migrations.RemoveField(
            model_name='zlecenie',
            name='adres_odbioru',
        ),
        migrations.RemoveField(
            model_name='zlecenie',
            name='user',
        ),
        migrations.DeleteModel(
            name='Zlecenie',
        ),
    ]
