# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-08 13:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Adres_app', '0004_auto_20171220_1323'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='adres',
            unique_together=set([('user', 'nazwa')]),
        ),
    ]
