# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-25 02:36
from __future__ import unicode_literals

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [
        ('Zlecenie_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zlecenie',
            name='data_zlozenia',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 25, 2, 36, 8, 234445, tzinfo=utc)),
        ),
    ]
