# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-04 09:25
from __future__ import unicode_literals

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [
        ('Zlecenie_app', '0004_auto_20180103_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zlecenie',
            name='data_zlozenia',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 4, 9, 25, 9, 185634, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='zlecenie',
            name='dystans',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
