# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-11 23:45
from __future__ import unicode_literals

import datetime

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Adres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ulica', models.CharField(max_length=200)),
                ('nr', models.CharField(max_length=20)),
                ('miasto', models.CharField(max_length=200)),
                ('kod_pocztowy', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Lista_Adresow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Lista_Zlecen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Zlecenie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_zlecenia', models.IntegerField(choices=[(1, 'Nowe'), (2, 'Przyjete'), (3, 'W oczekiwaniu na odbior'), (4, 'Dostawa'), (5, 'Zrealizowane')], default=1)),
                ('data_zlozenia', models.DateTimeField(default=datetime.datetime(2017, 12, 11, 23, 45, 22, 189581, tzinfo=utc))),
                ('data_odbioru', models.DateTimeField()),
                ('data_dostarczenia', models.DateTimeField()),
                ('adres_dostawy', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dostawa', to='Klient_app.Adres')),
                ('adres_odbioru', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='odbior', to='Klient_app.Adres')),
                ('lista_zlecen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Klient_app.Lista_Zlecen')),
            ],
        ),
        migrations.AddField(
            model_name='adres',
            name='lista_adresow',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Klient_app.Lista_Adresow'),
        ),
    ]
