# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-12 00:37
from __future__ import unicode_literals

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Klient_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lista_adresow',
            name='nazwa',
        ),
        migrations.AddField(
            model_name='adres',
            name='nazwa',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='zlecenie',
            name='data_zlozenia',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 12, 0, 37, 8, 172754, tzinfo=utc)),
        ),
    ]
