# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-12 11:19
from __future__ import unicode_literals

import datetime

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Klient_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(blank=True, max_length=200)),
                ('ulica', models.CharField(max_length=200)),
                ('nr', models.CharField(max_length=20)),
                ('miasto', models.CharField(max_length=200)),
                ('kod_pocztowy', models.CharField(max_length=10)),
                ('lista_adresow', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE,
                                                    to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Zlecenie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_zlecenia', models.IntegerField(
                    choices=[(1, 'Nowe'), (2, 'Przyjete'), (3, 'W oczekiwaniu na odbior'), (4, 'Dostawa'),
                             (5, 'Zrealizowane')], default=1)),
                ('data_zlozenia',
                 models.DateTimeField(default=datetime.datetime(2017, 12, 12, 11, 19, 6, 692799, tzinfo=utc))),
                ('data_odbioru', models.DateTimeField()),
                ('data_dostarczenia', models.DateTimeField()),
                ('adres_dostawy',
                 models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dostawa',
                                      to='Klient_app.Adres')),
                ('adres_odbioru',
                 models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='odbior',
                                      to='Klient_app.Adres')),
                ('lista_zlecen',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='adresy',
            name='user',
        ),
        migrations.RemoveField(
            model_name='zlecenia',
            name='user',
        ),
        migrations.DeleteModel(
            name='Adresy',
        ),
        migrations.DeleteModel(
            name='Zlecenia',
        ),
    ]
