# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-12 11:20
from __future__ import unicode_literals

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Klient_app', '0002_auto_20171212_1219'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adres',
            old_name='lista_adresow',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='zlecenie',
            old_name='lista_zlecen',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='zlecenie',
            name='data_zlozenia',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 12, 11, 20, 21, 187060, tzinfo=utc)),
        ),
    ]
