# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-12 01:16
from __future__ import unicode_literals

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Klient_app', '0002_auto_20171212_0137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zlecenie',
            name='data_zlozenia',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 12, 1, 16, 41, 266487, tzinfo=utc)),
        ),
    ]
