# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-14 12:35
from __future__ import unicode_literals

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [
        ('Klient_app', '0004_auto_20171212_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='zlecenie',
            name='faktura',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='zlecenie',
            name='wartosc',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='zlecenie',
            name='data_zlozenia',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 14, 12, 35, 36, 983718, tzinfo=utc)),
        ),
    ]
