# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-14 12:38
from __future__ import unicode_literals

import datetime

import django.db.models.deletion
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [
        ('Klient_app', '0005_auto_20171214_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zlecenie',
            name='adres_dostawy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dostawa',
                                    to='Klient_app.Adres'),
        ),
        migrations.AlterField(
            model_name='zlecenie',
            name='adres_odbioru',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='odbior',
                                    to='Klient_app.Adres'),
        ),
        migrations.AlterField(
            model_name='zlecenie',
            name='data_zlozenia',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 14, 12, 38, 14, 976755, tzinfo=utc)),
        ),
    ]
