# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-06 12:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='company_nr',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='nr',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
