# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-08 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Account_app', '0002_auto_20180106_1314'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='post_code',
            new_name='kod_pocztowy',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='company_post_code',
            new_name='kod_pocztowy_firmy',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='city',
            new_name='miasto',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='company_city',
            new_name='miasto_firmy',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='company',
            new_name='nazwa_firmy',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='company_nip',
            new_name='nip_firmy',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='nr',
            new_name='nr_domu',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='company_nr',
            new_name='nr_firy',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='phone',
            new_name='nr_telefonu',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='street',
            new_name='ulica',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='company_street',
            new_name='ulica_siedziby',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='telefon_firmy',
            field=models.IntegerField(default=0),
        ),
    ]
