# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-08 13:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('Account_app', '0003_auto_20180108_1443'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='nr_firy',
            new_name='nr_firmy',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='ulica_siedziby',
            new_name='ulica_firmy',
        ),
    ]
